phases:
- phase: Windows
  queue:
    name: Hosted VS2017
    timeoutInMinutes: 90
  steps:
    - task: PowerShell@2
      displayName: Set variables
      inputs:
        targetType: inline
        arguments: $(CODECOV_TOKEN)
        script: |
          Write-Host "##vso[task.setvariable variable=CODECOV_TOKEN;]$args[0]"
          $env:CODECOV_TOKEN = $args[0]
    - script: build\CIBuild.cmd -configuration $(_configuration) -prepareMachine
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\log'
        ArtifactName: 'logs'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\bin'
        ArtifactName: 'bin'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\VSSetup'
        ArtifactName: 'VSSetup'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishTestResults@2
      inputs:
        testRunner: 'xUnit'
        testResultsFiles: '**/*.xml' 
        searchFolder: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\TestResults'
        configuration: '$(_configuration)'
        publishRunAttachments: true
      continueOnError: true
      condition: always()